### ISSUE TITLE
XLXPEER support

### ISSUE THREAD

**Issue by sp2ong** [n0mjs710/HBmonitor#3]
Hi,

I have created a patch to add support XLXPEER in HBmonitor. It works  but maybe you can look on this patch 

[https://dvswitch.groups.io/g/main/attachment/4583/0/0001-Add-XLXPEERS-support.patch](https://dvswitch.groups.io/g/main/attachment/4583/0/0001-Add-XLXPEERS-support.patch)

I am not an advanced programmer maybe it is not an optimal solution

73 Waldek

**Comment by n0mjs710** [comment]
Don't open an issue, just send a pull request and I'll merge it.
